### PR TITLE
Organizing and Managing Open Source Events 章节翻译

### PR DESCRIPTION
**Pull request by gzchenyong**
保留了原文和中文，供翻译质量审核

### CODE REVIEW

**Comment by JuliaZhou2022** [comment]
I will do the review

**Comment by zRich** [comment]
@JuliaZhou2022  review 了吗？

**Comment by JuliaZhou2022** [comment]
Review finished. Please check and confirm the change made.

**Comment by node** [comment]
@gzchenyong  Cloud you please remove the original English from the translation content so that we can merge this PR later ?

**Comment by gzchenyong** [comment]
accept the review

**Pull request closed without merging**
